In [2]:
# packages
import pandas as pd
import numpy as np
import matplotlib as mpl
#import chartgazing as cg
from bs4 import BeautifulSoup
import requests
import json
import re

In [ ]:
# import pokemon names and numbers
url = "https://www.pokellector.com/Base-Set-Expansion/"

res = requests.get(url)
soup = BeautifulSoup(res.content, "html.parser")

pokemon = soup.select('.plaque')

pokemon_names = []

for entry in pokemon:
    try:
        pokemon_names.append(entry.get_text())
    except Exception as e:
        print(f"An error occurred: {e}")
        
print(pokemon_names[0:5])

pokemon_df = pd.DataFrame(pokemon_names, columns=['Pokemon'])

pokemon_df

['#1 - Alakazam', '#2 - Blastoise', '#3 - Chansey', '#4 - Charizard', '#5 - Clefairy']

                     Pokemon
0              #1 - Alakazam
1             #2 - Blastoise
2               #3 - Chansey
3             #4 - Charizard
4              #5 - Clefairy
..                       ...
97         #98 - Fire Energy
98        #99 - Grass Energy
99   #100 - Lightning Energy
100    #101 - Psychic Energy
101      #102 - Water Energy

[102 rows x 1 columns]

In [27]:
# test import of price data from pricecharting.com
url = "https://www.pricecharting.com/game/pokemon-base-set/charizard-1st-edition-4#completed-auctions-used"

html = requests.get(url, headers={"User-Agent": "Mozilla/5.0"}).text

chart_data = json.loads(re.search(r"VGPC\.chart_data\s*=\s*(\{.*?\});", html, re.S).group(1))

df = pd.DataFrame(
    [(grade, ts, price) for grade, points in chart_data.items() for ts, price, in points],
    columns =["grade", "date", "price"]
)

df["date"] = pd.to_datetime(df["date"], unit="ms")
df["price"] = df["price"] / 100

df

       grade                date     price
0    boxonly 2020-12-01 07:00:00      0.00
1    boxonly 2021-01-01 07:00:00      0.00
2    boxonly 2021-02-01 07:00:00  35794.50
3    boxonly 2021-03-01 07:00:00  57789.00
4    boxonly 2021-04-01 06:00:00  57789.00
..       ...                 ...       ...
421     used 2026-06-01 06:00:00   7495.70
422     used 2026-07-01 06:00:00   3049.73
423     used 2026-08-01 06:00:00   6650.00
424     used 2026-09-01 06:00:00   9541.19
425     used 2026-10-01 06:00:00   9057.92

[426 rows x 3 columns]